app:
  name: rai
  verbose: false
  debug: false
aws:
  access_key_id: +NPjNiwCtTNvMUg94O/PVGOPc1N6ExBx7Lyz3TGRuIqVfqFoYuRNEl1gkZw=
  secret_access_key: onXRqpVtlebXW+dN5atvjpZGuyNH8pzkAD7tx7diCj9rnByX9+BxlESV1ehoo7D7BtoDCDf73uLYVqXDQvdOq5JoL9AAFdIr
  region: us-east-1
  sts_account: 122130270846
  sts_role: rai
store:
  provider: s3
  base_url: http://s3.amazonaws.com
  acl: public-read
client:
  name: rai
  upload_bucket: files.rai-project.com
  bucket: userdata
  build_file: rai_build
auth:
  provider: auth0
  domain: raiproject.auth0.com
  encrypted_client_id: 59Eg6+hFDfkoeZCkQvSUo0sgCsHcu1B9MoGgANkwyzJqgtVfQr7IG6iY+awG8abQPUmnaaAqJrYfbtxO
  encrypted_client_secret: 2pOhrh3oRAs+o6h1Z7kcM4w6LpFjL67+j2vBTMGpS91jtBO42wKGjkIUTCtqUukMy2K/5VmzL125YcuPnwiVbZiwXTrmr8O/gW8H/DOGEWCjI5dqcaHhIsMFVEWT5GNbw1/moxb4sF4=
pubsub:
  endpoints:
    - pubsub.rai-project.com:6379
  encrypted_password: SnY+X9yvTpvVRWo+hqq1Bjup8vvYEtDURcsO2w==
